= Notes on giving a presentation
:toc: preamble

This article describes a couple of notes on giving a presentation at a
conference or meetup. It's made based off of the good and not so good things
I've seen from the presentations given by others, and some things I've learned
while presenting myself.

== Slides
Your slides are probably the most important aspect of your talk. It can use
images to give your audience an easy reference point or describe a context.
It's also a great way to show a snippet of code.

=== Tools for making your slides
Making a "cloud" based slideshow (such as with Google Docs) is not recommended,
as you can't guarantee there'll be a stable Internet connection available.

The format of your slideshow is also important. Try to make it as agnostic as
possible. If things go wrong, you should be able to use a backup device to
present with. If your slide is made with LibreOffice for instance, there's a
big chance you can't open your slides on the backup device.

Hence, I would recommend using a tool to create a standalone, HTML based
slideshow. I've yet to see a backup device that did not have Chromium or
Firefox available. You're very likely to have either of these, or
another compatible browser, already installed on your own system.

There's a couple solutions to make these with little effort. To name a few:

* https://github.com/partageit/markdown-to-slides
* https://github.com/neo4j-contrib/asciidoc-slides

=== Making good slides
Having slides is good. Having good slides is the best. They'll help you to
bring your message across. There are some common mistakes in many slideshows.
There's no reason for you to make the same mistakes, so I've made a list of
things to keep in mind.

==== Font size

==== Colors


==== Content
Keep the content consise. Use a couple of keywords to denote what you're
talking about. Don't use full sentences. These will distract the audience into
reading a lot and not hearing what you're saying.

== Supplies
You'll need some equipment to give a good talk. At least you'll need to have
something to actually present. You should also expect things to go wrong, and
you want to be able to cope with these things. Therefore I'll supply a list of
things you should bring, which you can use as a checklist.

=== Your own device to present with
It's very common for tech conferences or meetups to expect you to bring your
own device to present on, usually in the form of a laptop. The most common
connector to have available at conferences seems to be HDMI. If your device
doesn't have a standard HDMI out port, be sure to bring a converter from
whatever your device supports to HDMI.

=== A backup device to present with
Things always go wrong at the worst times. This is also the case for
presentations. It's not uncommon for someone's device to have difficulties
when the presentation is about to start. Whether it doesn't interface well with
the hardware provided by the conference or some update last night broke your X
setup doesn't matter at this point in time.

Get a cheap device, install an "easy" OS on it that you can be sure will work
to at least be able to run your slideshow.

=== A USB stick with your slideshow
A USB stick is cheap to get, and small to bring everywhere. It's a last resort
in case your device(s) doesn't work properly for any reason. Having a slideshow
in a format that doesn't require other packages to be installed is a great
benefit to have here.

== Presenting

=== Bring a laserpointer with prev/next buttons

=== Speak up!

=== Introduce yourself

=== Non-verbal communication

=== Live coding
Never.

=== Leave time for comments and questions

=== Track your time
